### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Abeera-Tariq** [reenaishtiaq/mockup-may-23#3]
Try adding more responsivity for icons, etc
![image](https://user-images.githubusercontent.com/35397213/58701821-75355d80-83bd-11e9-835c-9655a7697080.png)

**Comment by Abeera-Tariq** [comment]
The icons are still not responsive. Ooper wali picture mei jo icons hain unko bhi hover pe change karayin.

**Comment by KhairUnNisa10** [comment]
![image](https://user-images.githubusercontent.com/49787331/59161741-d36de900-8aff-11e9-9bfd-5b77d45d5f49.png)

Make the message at its full length in responsive. 
Insert the Navigation bar at the top.

![image](https://user-images.githubusercontent.com/49787331/59161753-f4363e80-8aff-11e9-8971-dbbeb295f1d9.png)

Centrally align the dates.

**Comment by Abeera-Tariq** [comment]
Dates are still not centrally aligned
